version: '3.8'

services:
  postgres:
    build:
      context: ./postgres/
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    env_file: ../../.env
    container_name: server-postgres
    ports:
      - '5434:5432'
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    env_file: ../../.env
    container_name: server-pgadmin
    ports:
      - '6434:6432'
    restart: always
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres
